env:
    browser: true
    es2021: true
    node: true
extends:
    - prettier
overrides: []
parser: "@typescript-eslint/parser"
parserOptions:
    ecmaVersion: latest
    sourceType: module
plugins:
    - react
    - "@typescript-eslint"
rules:
    indent:
        - error
        - 4
    linebreak-style:
        - error
        - unix
    quotes:
        - error
        - double
    semi:
        - error
        - always
    no-multiple-empty-lines:
        - error
        - max: 1
    no-irregular-whitespace:
        - error
        - skipStrings: true
